var quotes = [
    'Happiness Is A Butterfly.',
    'It\'s not fashionable to love me.',
    'I feel free when I see no one and nobody knows my name.',
    'I\'ve got nothing much to live for ever since I found my fame.',
    'Loving me is all you need to feel.',
    'Got my blue nail polish on. It\'s my favorite color and my favorite tone of song.',
    'You know sometimes, baby, I\'m so carefree.',
    'I keep my lips red to seem like cherries in the spring.',
    'Blue hydrangea, cold cash, divine, cashmere, cologne and white sunshine.',
    'What I do, I do best.',
    'I fucked my way up to the top.',
    'I want money, power, and glory.',
    'I\'m pretty when I cry.',
    'They judge me like a picture book by the colors, like they forgot to read.',
    'I was filled with poison, but blessed with beauty and rage.',
    'In the land of gods and monsters, I was an angel.',
    'My pussy taste like Pepsi-Cola.',
    'My eyes are wide like cherry pies.',
    'Done my hair up real big beauty queen style.',
    'It\'s alarming honestly how charming she can be.',
    'I know what the boys want, I\'m not gonna play.',
    'I\'m your national anthem.',
    'He said to "be cool" but I\'m already coolest.',
    'Um, do you think you\'ll buy me lots of diamonds?',
    'You\'re my religion. You\'re how I\'m living.',
    'Every now and then the stars align, boy and girl meet by the great design.',
    'I know what only the girls know.',
    'Looking back, my past it all seems stranger than a stranger.',
    'The power of youth is on my mind.',
    'I pledge allegiance to my dad for teaching me everything he knows.',
    'And there\'s no remedy for memory.',
    'All I wanna do is get high by the beach.',
    'Club queen on the downtown scene.',
    'You\'re so art deco, out on the floor.',
    'A little party never hurt no one, we were born to be free.',
    'Why work so hard when you could just be free?',
    'Writing all of my songs about my cheap thrills.',
    'Life is awesome, I confess.',
    'Down on the West Coast they got a saying, if you\'re not drinkin then you\'re not playin.',
    'Get a little bit of bourbon in ya.',
    'Get a little bit suburban and go crazy.',
    'Because you\'re young, you\'re wild, you\'re free You\'re dancin circles around me.',
    'We get down every Friday night, dancin\' and grindin\' in the pale moonlight.',
    'Drinkin\' cherry schnapps in the velvet night.',
    'The prettiest in crowd that you had ever seen, ribbons in our hair and our eyes gleamed mean',
    'Now my life is sweet like cinnamon, like a fucking dream I\'m living in.',
    'Money is the anthem of success, so put on mascara, and your party dress.',
    'Sometimes I wake up in the morning to red, blue, and yellow skies.',
    'Sun and ocean blue, their magnificence, it don\'t make sense to you.',
    'Life is beautiful but you don\'t have a clue.',
    'We can escape to the great sunshine.',
    'Diet Mountain Dew, baby, New York City. Never was there ever a girl so pretty',
    'You got the world, but baby, at what price? It\'s something so strange, it\'s hard to define',
    'Playing games of levitation. Meditating in the garden',
    'Sometimes love is not enough and the road gets tough',
    'I fall to pieces when I\'m with you, I fall to pieces. My cherries and wine, rosemary and thyme',
    'I\'ve seen the world, lit it up as my stage now. Channeling angels in the new age now',
    'You get ready, you get all dressed up, to go nowhere in particular',
    'Writing in blood on my walls cause the ink in my pen don\'t work in my notepad',
    'It escapes from my hands into moonlight',
    'Dive in, dive deep and in dark blue my sweet brushing up from the water where the ice meets',
    'Heaven is a place on Earth with you, tell me all the things you wanna do'


]

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];



}